# #### 3) Think Stats Exercise 4.2

# The numbers generated by `random.random` are supposed to be uniform between 0 and 1; that is, every value in the range should have the same probability.

# Generate 1000 numbers from `random.random` and plot their PMF and CDF. Is the distribution uniform?
